# Generated by Django 4.1.7 on 2023-03-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_ingredients_ingredient_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='id',
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='ingredient_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
