# Generated by Django 4.1.7 on 2023-03-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_ingredients_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='ingredient_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
