# Generated by Django 3.2.18 on 2023-03-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20230327_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='new_ingredient',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
