# Generated by Django 3.2.18 on 2023-03-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_ingredients_ingredient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='new_ingredient',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
