# Generated by Django 3.2.18 on 2023-03-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_ingredients_ingredient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='ingredient_name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='new_ingredient',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
