# Generated by Django 3.2.18 on 2023-04-04 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='new_ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='accounts.ingredients'),
        ),
    ]
