# Generated by Django 3.2.18 on 2023-04-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_remove_recipe_new_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
    ]
